name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start Application
        env:
          apiKey: ${{ secrets.apiKey }}
          authDomain: ${{ secrets.authDomain }}
          databaseURL: ${{ secrets.databaseURL }}
          projectId: ${{ secrets.projectId }}
          storageBucket: ${{ secrets.storageBucket }}
          messagingSenderId: ${{ secrets.messagingSenderId }}
          appId: ${{ secrets.appId }}
          measurementId: ${{ secrets.measurementId }}
        run: node server.js

  run-tests:
    needs: start-server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm test
