name: Node.js CI/CD

on:
  push:
    branches:
      - main # ajuste conforme sua branch principal
      - develop

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start Application
        run: node server.js

  run-tests:
    needs: start-server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
